package:
  name: humanfilt
  version: 0.1.0

source:
  url: https://github.com/jprehn-lab/humanfilt/archive/refs/tags/v0.1.0.tar.gz
  sha256: 0f9f96e41e019181bcc15fa0bad0d8c2494032c9fb6d0a8d9bd00799715e8824

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - humanfilt=humanfilt.cli:main

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
  run:
    - python >=3.10
    - bwa
    - samtools
    - minimap2
    - bowtie2
    - kraken2
    - trim-galore
    - bbmap
    - fastuniq
    - seqkit
    - pigz

test:
  imports:
    - humanfilt
  commands:
    - humanfilt --help

about:
  home: https://github.com/jprehn-lab/humanfilt
  license: MIT
  summary: "WGS human-read filtering with auto-downloaded human references"

extra:
  recipe-maintainers:
    - marsfro
