package.version: 0.1.0
source.url: https://github.com/jprehn-lab/humanfilt/archive/refs/tags/v0.1.0.tar.gz
source.sha256: 0f9f96e41e019181bcc15fa0bad0d8c2494032c9fb6d0a8d9bd00799715e8824
about.home: https://github.com/jprehn-lab/humanfilt
extra.recipe-maintainers: marsfro
